<a href="https://colab.research.google.com/github/amritxcode/AgenticAI_DevSummit_2026/blob/main/numpy_pandas_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy & Pandas Fundamentals Practice Notebook

## NumPy Basics

In [ ]:
#Creating Array 1D 2D
import numpy as np

arr1d = np.array([1,2,3,4,5])
print(arr1d)

arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# element-wise operators
a = np.array([1,2,3])
b = np.array([10,20,30])
print(a + b)
print(a * b)
print(a - b)

[11 22 33]
[10 40 90]
[ -9 -18 -27]


In [ ]:
#Matrix multiplication
m1 = np.array([[1,2], [3,4]])
m2 = np.array([[5,6], [7,8]])
print(np.dot(m1,m2))

[[19 22]
 [43 50]]


In [ ]:
arr = np.array([1,2,3,4,5,6])
reshaped = arr.reshape(3,2)
print(reshaped)

flat = reshaped.flatten()
print(flat)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])
print(arr[1:3])

arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d[:,2])

10
[20 30]
[3 6]


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr + 10)
arr_1d = np.array([1,0,1])
print(arr + arr_1d)

[[11 12 13]
 [14 15 16]]
[[2 2 4]
 [5 5 7]]


In [ ]:
import time
big_list = list(range(1000000))
big_array = np.array(big_list)

start = time.time()
result_loop = [x * 2 for x in big_list]
print("Loop time:", time.time() - start)

start = time.time()
result_vec = big_array * 2
print("Vectorized time:", time.time() - start)

Loop time: 0.12087726593017578
Vectorized time: 0.00438380241394043


In [ ]:
arr = np.array([1,2,3,4,5])
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))

print(np.zeros((2,3)))
print(np.ones((2,3)))
print(np.random.randn(3,3))

15
3.0
5
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[-0.03524772  0.20435094  2.18113656]
 [-0.55171597  0.88401291  0.87112914]
 [ 0.37922162  0.48154657 -0.96162759]]


## Pandas — Missing Pieces